services:
  postgres:
    image: postgres:16
    container_name: greenlight_db
    environment:
      POSTGRES_USER: owen
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: greenlight
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: